[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"
  NEXT_TELEMETRY_DISABLED = "1"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Optional: if using a server database with Prisma, use this build command instead:
# [build]
#   command = "npx prisma generate && npx prisma migrate deploy && npm run build"

